[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# El QR apunta a /r/<codigo> -> función que cuenta y redirige
[[redirects]]
  from = "/r/*"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true

# API del panel
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
